# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    concurrency: deploy-group    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install --force

      - name: Run tests
        run: npm run test

      - name: Run eslint
        run: npm run eslint
        
      - name: Setup flyctl
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    notifyDiscord:
      needs: [simple_deployment_pipeline]
      runs-on: ubuntu-latest
      uses: sarisia/actions-status-discord@v1
      if: failure()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        content: "Hey <@675998523770011659>"
        status: ${{ job.status }} 
        title: "deploy"
        description: |
          **Repository:** ${{ github.repository }}
          **Branch:** ${{ github.ref_name }}
          **Commit:** ${{ github.sha }}
          **Message:** ${{ github.event.head_commit.message }}
          **Author:** ${{ github.actor }}
        color: 0xfd413f
        
        username: "Fullstack part 11 Hook"