name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello World!"
  print_date_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run date command 
        run: |
            date
  file_contents_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run list file command 
        run: |
            ls -l