name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello World!"
      - name: Run date command 
        run: |
            date
      - name: Run list file command 
        run: |
            ls -l
      - name: Discord notification
        uses: sarisia/actions-status-discord@v1
        if: always() # Ensures it runs on both success and failure
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }} 
          title: ${{ job.status == 'success' && 'Deployment Successful!' || 'Build Failed!' }}
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}
          color: ${{ job.status == 'success' ? 0x28a745 : 0xcb2431 }}
          username: "Fullstack part 11 Hook"